SELECT DISTINCT c.car_id
FROM CAR_RENTAL_COMPANY_CAR c
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h ON c.car_id = h.car_id
WHERE c.car_type = '세단'
  AND h.start_date BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY c.car_id DESC;
